<a href="https://colab.research.google.com/github/Vijay123123/CricketScorePredictorml/blob/main/CricketScorePredictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/t20i/t20i_info.csv')
import numpy as np

df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [ ]:
# batting team
# bowling team
# city
# current s core
# ball left
# wickets left
# current rr
# last five overs

In [ ]:
# Pre-Processing

df.isnull().sum()

Unnamed: 0             0
match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8548
venue                  0
dtype: int64

In [ ]:
# Replacing null values in city ( So we are trying to replace the venues in place of null cities )

cities=np.where(df['city'].isnull(),df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [ ]:
df['city']=cities
df['city'].isnull().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Unnamed: 0          0
match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [ ]:
df.drop(columns='venue',inplace=True)

In [ ]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo

In [ ]:
# Considering only few cities where balls throwed more than 600 i.e 5 matches
eligible_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [ ]:
df=df[df['city'].isin(eligible_cities)]

In [ ]:
df['current_score']=df.groupby('match_id')['runs'].cumsum()
df

/tmp/ipykernel_7823/4061384524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score']=df.groupby('match_id')['runs'].cumsum()

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3
...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,125
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,125
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,127
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [ ]:
df['over']=df['ball'].apply(lambda x:str(x).split(".")[0])
df['balls']=df['ball'].apply(lambda x:str(x).split(".")[1])

/tmp/ipykernel_7823/4002706395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over']=df['ball'].apply(lambda x:str(x).split(".")[0])
/tmp/ipykernel_7823/4002706395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls']=df['ball'].apply(lambda x:str(x).split(".")[1])

In [ ]:
df['balls_bowled']=(df['over'].astype('int')*6+df['balls'].astype('int'))

/tmp/ipykernel_7823/824444643.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled']=(df['over'].astype('int')*6+df['balls'].astype('int'))

In [ ]:
df['balls_left']=120-df['balls_bowled']
df['balls_left']=df['balls_left'].apply(lambda x:0 if x<0 else x)

/tmp/ipykernel_7823/3502974883.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left']=120-df['balls_bowled']
/tmp/ipykernel_7823/3502974883.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left']=df['balls_left'].apply(lambda x:0 if x<0 else x)

In [ ]:
df['players_dismissed']=df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
df['players_dismissed']=df['players_dismissed'].astype('int')
df['players_dismissed']=df.groupby('match_id')['players_dismissed'].cumsum()
df['wickets_left']=10-df['players_dismissed']

/tmp/ipykernel_7823/3878040286.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['players_dismissed']=df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
/tmp/ipykernel_7823/3878040286.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['players_dismissed']=df['players_dismissed'].astype('int')
/tmp/ipykernel_7823/3878040286.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['players_dismissed']=df.groupby('match_id')['players_dismissed'].cumsum()
/tmp/ipykernel_7823/3878040286.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left']=10-df['players_dismissed']

In [ ]:
df['crr']=(df['current_score']*6)/df['balls_bowled']

/tmp/ipykernel_7823/1648461935.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr']=(df['current_score']*6)/df['balls_bowled']

In [ ]:
df

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,balls,balls_bowled,balls_left,players_dismissed,wickets_left,crr
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,0,10,0.000000
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,0,10,0.000000
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,0,10,2.000000
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,0,10,4.500000
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,0,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3,8,2,6.410256
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2,8,2,6.355932
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1,9,1,6.302521
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0,9,1,6.350000
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0,9,1,6.347107

In [ ]:
# for getting something over a window can be done using pandas funcs
from pandas.tseries.offsets import LastWeekOfMonth
groups=df.groupby('match_id')
match_ids=df['match_id'].unique()
last_five=[]
for id in match_ids:
  last_five.extend(groups.get_group(id)['runs'].rolling(window=30).sum().values.tolist())

In [ ]:
# last_five overs runs for every match by window method to calculate it

In [ ]:
df['last_five']=last_five
df

/tmp/ipykernel_7823/678253765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five']=last_five

,Unnamed: 0,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,balls,balls_bowled,balls_left,players_dismissed,wickets_left,crr,last_five
0,0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,0,10,0.000000,NaN
1,1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,0,10,0.000000,NaN
2,2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,0,10,2.000000,NaN
3,3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,0,10,4.500000,NaN
4,4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,0,10,3.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63883,121,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3,8,2,6.410256,32.0
63884,122,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2,8,2,6.355932,32.0
63885,123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1,9,1,6.302521,32.0
63886,124,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0,9,1,6.350000,33.0
63887,125,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0,9,1,6.347107,32.0

In [ ]:
df=df.groupby('match_id').sum()['runs'].reset_index().merge(df,on='match_id')

In [ ]:
df=df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [ ]:
df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
29,Australia,Sri Lanka,Melbourne,43,90,10,8.600000,43.0,168
30,Australia,Sri Lanka,Melbourne,44,89,10,8.516129,44.0,168
31,Australia,Sri Lanka,Melbourne,45,88,10,8.437500,45.0,168
32,Australia,Sri Lanka,Melbourne,45,87,10,8.181818,44.0,168
33,Australia,Sri Lanka,Melbourne,45,86,10,7.941176,42.0,168
...,...,...,...,...,...,...,...,...,...
50496,Sri Lanka,Australia,Colombo,125,3,2,6.410256,32.0,128
50497,Sri Lanka,Australia,Colombo,125,2,2,6.355932,32.0,128
50498,Sri Lanka,Australia,Colombo,125,1,1,6.302521,32.0,128
50499,Sri Lanka,Australia,Colombo,127,0,1,6.350000,33.0,128
50500,Sri Lanka,Australia,Colombo,128,0,1,6.347107,32.0,128

In [ ]:
df=df.sample(df.shape[0])
# Shuffling to avoid biased output randomizing rows

In [ ]:
df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
36451,Australia,Sri Lanka,Sydney,106,24,7,6.625000,42.0,137
3108,Pakistan,West Indies,Trinidad,134,2,2,6.813559,28.0,137
20569,England,South Africa,Nottingham,36,69,7,4.235294,21.0,111
46720,South Africa,Sri Lanka,Cape Town,138,15,5,7.885714,32.0,169
25029,New Zealand,Pakistan,Barbados,75,47,6,6.164384,28.0,133
...,...,...,...,...,...,...,...,...,...
14995,Sri Lanka,New Zealand,Auckland,61,46,3,4.945946,16.0,115
40742,Bangladesh,Australia,Mirpur,51,73,8,6.510638,43.0,153
37047,Sri Lanka,Bangladesh,Pallekele,166,14,6,9.396226,58.0,198
16825,Australia,Pakistan,Johannesburg,75,77,8,10.465116,56.0,164
38546,West Indies,New Zealand,Wellington,89,40,6,6.675000,29.0,159

In [ ]:
X=df.drop(columns=['runs_x'])
y=df['runs_x']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)  # 30k rows for training remaining for testing

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [ ]:
trf=ColumnTransformer(
    [('trf',OneHotEncoder(sparse_output=False,drop='first'),['batting_team','bowling_team','city'])],remainder='passthrough'
)

# One hot Encoding 'batting_team','bowling_team','city' attributes

In [ ]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder, StandardScaler
# from sklearn.pipeline import Pipeline
# from sklearn.ensemble import RandomForestRegressor

categorical_features = ['batting_team', 'bowling_team', 'city']
numerical_features = ['current_score', 'balls_left', 'wickets_left', 'crr', 'last_five']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(sparse_output=False, drop='first'), categorical_features),
        ('num', StandardScaler(), numerical_features)
    ],
    remainder='passthrough'
)

rf_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=100, random_state=1))
])

rf_pipeline.fit(X_train, y_train)
print("RandomForestRegressor pipeline created and trained successfully.")

RandomForestRegressor pipeline created and trained successfully.

In [ ]:
y_pred_rf = rf_pipeline.predict(X_test)

r2_rf = r2_score(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)

print(f"RandomForestRegressor R-squared: {r2_rf:.4f}")
print(f"RandomForestRegressor Mean Absolute Error: {mae_rf:.4f}")

RandomForestRegressor R-squared: 0.9771
RandomForestRegressor Mean Absolute Error: 2.0873

In [ ]:
xgb_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', XGBRegressor(n_estimators=1000, random_state=1, learning_rate=0.2,max_depth=12))
])


xgb_pipeline.fit(X_train, y_train)
print("XGBRegressor pipeline created and trained successfully.")

XGBRegressor pipeline created and trained successfully.

In [ ]:
y_pred_xgb = xgb_pipeline.predict(X_test)

r2_xgb = r2_score(y_test, y_pred_xgb)
mae_xgb = mean_absolute_error(y_test, y_pred_xgb)

print(f"XGBRegressor R-squared: {r2_xgb:.4f}")
print(f"XGBRegressor Mean Absolute Error: {mae_xgb:.4f}")

XGBRegressor R-squared: 0.9895
XGBRegressor Mean Absolute Error: 1.5494

In [ ]:
print(f"\n--- Model Performance Comparison ---")
print(f"RandomForestRegressor R-squared: {r2_rf:.4f}")
print(f"RandomForestRegressor Mean Absolute Error: {mae_rf:.4f}")
print(f"XGBRegressor R-squared: {r2_xgb:.4f}")
print(f"XGBRegressor Mean Absolute Error: {mae_xgb:.4f}")

if r2_rf > r2_xgb and mae_rf < mae_xgb:
    print("\nBased on the R-squared and Mean Absolute Error, RandomForestRegressor performed better.")
elif r2_xgb > r2_rf and mae_xgb < mae_rf:
    print("\nBased on the R-squared and Mean Absolute Error, XGBRegressor performed better.")
else:
    print("\nThe performance of both models is comparable or requires further analysis to determine a clear winner.")

--- Model Performance Comparison ---
RandomForestRegressor R-squared: 0.9771
RandomForestRegressor Mean Absolute Error: 2.0873
XGBRegressor R-squared: 0.9895
XGBRegressor Mean Absolute Error: 1.5494

Based on the R-squared and Mean Absolute Error, XGBRegressor performed better.

In [ ]:
import pickle

with open("xgb_pipeline.pkl", "wb") as f:
    pickle.dump(xgb_pipeline, f)